### ISSUE TITLE
URL pattern

### ISSUE THREAD

**Issue by TT1943** [osfinance/os-finance#27]
each 'dapp' should have its own root, and move all its functions under that root
for example
os.finance/#/compound
os.finance/#/deerfi
os.finance/#/sushiswap
os.finance/#/sushiswap/swap
os.finance/#/sushiswap/pool
os.finance/#/uniswap
os.finance/#/uniswap/swap
os.finance/#/uniswap/pool

**Comment by DreamXzxy** [comment]
https://github.com/osfinance/os-finance/pull/28
