### ISSUE TITLE
Page will crash after click update token list button if the router is not is not sushi or uniswap.

### ISSUE THREAD

**Issue by DreamXzxy** [osfinance/os-finance#38]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**
1. Go to ...
2. Click on ...
...

**Expected Behavior**

**Additional Context**
![image](https://user-images.githubusercontent.com/17998878/104024953-e0345080-51fe-11eb-9b70-aa56f846ad78.png)

![image](https://user-images.githubusercontent.com/17998878/104024875-bed36480-51fe-11eb-84f1-d118d5377d2f.png)

**Comment by qiuchenghui** [comment]
Fix on [PR](https://github.com/osfinance/os-finance/pull/39)
